name: Build and deploy ASP.Net Core app to Azure Web App - maintenance-webapi-8824576

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore Maintenance.WebAPI/Maintenance.WebAPI.csproj

      - name: Build
        run: dotnet build Maintenance.WebAPI/Maintenance.WebAPI.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Maintenance.WebAPI/Maintenance.WebAPI.csproj -c Release -o publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'maintenance-webapi-8824576'
          package: publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_626908BC296D472D8E75F8E56C79590D }}
